export const DATACENTERS = [
  {
    id: 'DC-01',
    name: 'Permian Compute Campus',
    location: 'Odessa, TX',
    lat: 31.85,
    lng: -102.37,
    photo: '/images/datacenter.png',
    technology: 'SMR',
    demand: '1.2 GW',
    transmission: 'Behind-the-meter',
  },
  {
    id: 'DC-02',
    name: 'Oak Ridge AI Center',
    location: 'Oak Ridge, TN',
    lat: 36.01,
    lng: -84.27,
    photo: '/images/smr.png',
    technology: 'Microreactor',
    demand: '300 MW',
    transmission: '161 kV',
  },
  {
    id: 'DC-03',
    name: 'Shenandoah Hyperscale',
    location: 'Harrisonburg, VA',
    lat: 38.45,
    lng: -78.87,
    photo: '/images/coolingtower.png',
    technology: 'AP1000',
    demand: '2 GW',
    transmission: '500 kV',
  },
  {
    id: 'DC-04',
    name: 'Columbia River Cluster',
    location: 'Richland, WA',
    lat: 46.29,
    lng: -119.28,
    photo: '/images/datacenter.png',
    technology: 'SMR',
    demand: '960 MW',
    transmission: '230 kV',
  },
  {
    id: 'DC-05',
    name: 'Platte Valley Data Park',
    location: 'Kearney, NE',
    lat: 40.7,
    lng: -99.08,
    photo: '/images/smr.png',
    technology: 'SMR',
    demand: '800 MW',
    transmission: '345 kV',
  },
  {
    id: 'DC-06',
    name: 'Great Basin Edge',
    location: 'Ely, NV',
    lat: 39.25,
    lng: -114.89,
    photo: '/images/datacenter.png',
    technology: 'Microreactor',
    demand: '50 MW',
    transmission: 'Islanded',
  },
  {
    id: 'DC-07',
    name: 'Savannah River Campus',
    location: 'Aiken, SC',
    lat: 33.56,
    lng: -81.72,
    photo: '/images/coolingtower.png',
    technology: 'AP1000',
    demand: '1.5 GW',
    transmission: 'Co-located',
  },
  {
    id: 'DC-08',
    name: 'Lakeshore Compute',
    location: 'Covert, MI',
    lat: 42.32,
    lng: -86.31,
    photo: '/images/coolingtower.png',
    technology: 'PWR Restart',
    demand: '800 MW',
    transmission: '345 kV',
  },
];
